### ISSUE TITLE
Compilation error with Coq 8.6

### ISSUE THREAD

**Issue by smarter** [ildyria/CompCert#1]
```shell
COQC lib/Coqlib.v
File "./lib/Coqlib.v", line 24, characters 15-21:
Error: Unable to locate library FunInd.
Makefile:184: recipe for target 'lib/Coqlib.vo' failed
```

Removing `Require Export FunInd.` from `Coqlib.v` fixes the issue.

**Comment by ildyria** [comment]
`Require Export FunInd` is required for Coq 8.7 and is provided by 8.6.1.

**Solution:** Dropping support for Coq.8.6. Sorry.
